project:
  type: website
  output-dir: docs

author:
  - id: a
    number: 1
    name: 
      given: Kun
      family: Hou
      literal: Kun Hou
    orcid: 0000-xxxx-xxxx-xxxx
    email: xxx@163.com
    attributes:
      corresponding: false
    roles: 
      - conceptualization
      - methodology
      - writing – original draft
    affiliations:
      - id: xju
        number: 1
        name: Health Science Center, Xi’an Jiaotong University
        department: Health Science Center
        city: Xi'an
        address: address
        region: Shaanxi
        country: China
        postal-code: 710061
      
      - id: hztcm
        name: Hanzhong Traditional Chinese Medicine Hospital
        department: department
        address: address
        city: Hanzhong
        region: Shaanxi
        country: China
        postal-code: 723001
        
  - id: b
    number: 2
    name: 
      given: Xili
      family: Wu
      literal: Xili Wu
    orcid: 0000-xxxx-xxxx-xxxx
    email: xxx@163.com
    attributes:
      corresponding: true
    roles:
      - project administration
      - funding
    affiliations:
      - ref: xju
      - name: The Second Affiliated Hospital of Xi’an Jiaotong University
        department: department
        address: address
        city: Xi'an
        region: Shaanxi
        country: China
        postal-code: 710061

bibliography: references.bib
csl: multidisciplinary-digital-publishing-institute.csl

website:
  title: "ZWHQD for HFrEF"
  description: "Integrating Network Pharmacology, Multi-Omics, Causal Inference & Molecular Docking"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: paper.qmd
        text: Paper
      - href: manu01.qmd
        text: Manuscript01
      - href: manu.qmd
        text: Manuscript
      - text: Scripts
        menu:
          - text: "0.Install Required Packages"
            href: "scripts/00_install_required_packages.qmd"
          - text: "1.Acquisition of Active Compounds, Targets and HCT Network Construction"
            href: "scripts/01_compounds_target_prediction.qmd"
          - text: "2.Transcriptomic Data Acquisition and DCM-CHF Disease Target Screening"
            href: "scripts/02_bulk_rna_deg_wgcna.qmd"
          - text: "3.PPI Network Construction and Hub Target Identification"
            href: "scripts/03_ppi_hub_genes.qmd"
          - text: "4.Tissue Specific Expression Profiling of Hub Targets"
            href: "scripts/04_organ_localization.qmd"
          - text: "5.Functional Enrichment Analysis"
            href: "scripts/05_functional_enrichment.qmd"
          - text: "6.Immune Infiltration Analysis"
            href: "scripts/06_immune_infiltration_quantification.qmd"
          - text: "7.MR and Colocalization"
            href: "scripts/07_mr_colocalization.qmd"
          - text: "8.Single cell analysis and ssGSEA"
            href: "scripts/08_single_cell_analysis_ssGSEA.qmd"
          - text: "9.Molecular Docking Analysis"
            href: "scripts/09_molecular_docking_analysis.qmd"
          - text: "10.Figures and Tables"
            href: "scripts/10_figures_and_tables.qmd"

format:
  # docx:
  #   toc: false
  # html:
  wordcount-html:
    css: style.css
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: false 
    code-fold: false
    code-tools: false
    code-copy: true
    code-line-numbers: true
    highlight-style: github
    tbl-cap-location: top
    supptbl-cap-location: top
    fig-align: center
    fig-dpi: 300
    page-layout: full
    smooth-scroll: true

crossref:
  title-delim: "."
  subref-labels: alpha A
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      latex-list-of-description: Supplementary Figure
      space-before-numbering: false
    - kind: float
      key: supptbl
      latex-env: supptbl
      reference-prefix: Table S
      latex-list-of-description: Supplementary Table
      space-before-numbering: false

execute:
  eval: false
  echo: true
  warning: false
  message: false