---
title: "Synergistic Mechanisms of *Aconitum carmichaelii* Debeaux and *Astragalus membranaceus* Combination Against Chronic Heart Failure Due to Dilated Cardiomyopathy: Insights from Multi–Omics and Causal Inference"
format: 
  #html:
  wordcount-html:
    toc: true
    number–sections: true

abstract: >
  Background: Among gynecological malignancies, ovarian cancer (OC) remains a leading cause of mortality worldwide, often characterized by the highest fatality-to-case ratio due to its asymptomatic progression and late-stage detection. Despite substantial investigation, the root cause of disease development and pathology remains unknown. Early detection is critical for improving OC prognosis. Unfortunately, because of the lack of identifiable symptoms in the early stages, the disease is frequently detected late. As a result, regular check-ups, being aware of risk factors, and paying attention to unusual symptoms can all help discover OC early. Apolipoproteins (APOs) and Annexins (ANXs) have recently been linked to OC. Aim: We conducted a cutting-edge bioinformatics investigation to find novel therapeutic targets and precise biomarkers linked to OC against APO and ANX. Methods: We started by compiling the ANX and APO families via HUGO Gene Nomenclature Committee (HGNC) homepage. Next, we accessed GEPIA2 to compare the relative messenger RNA (mRNA) expression levels of all ANX and APO family members across the cancer genome atlas (TCGA)-OC cohort and matched normal and GTEx data. Prognostic analysis of all significantly expressed ANXs and APOs was performed via Kaplan–Meier (KM) plotter. cBioPortal was used for mutational analysis of prognostic ANXs and APOs. Finally, we ran functional enrichment, molecular docking, and molecular dynamics (MD) simulation analyses. Results: Overall, the results suggest that ANXA2 and its related genetic changes represent potential focal points for precision oncology, offering a computational rationale for the development of target-driven therapeutic interventions in OC. Conclusions: Molecular docking and MD simulation analyses identified curcumin as a potential inhibitor of ANXA2, demonstrating stable binding affinity and structural conservation throughout the simulation period. These computational findings characterize curcumin as a promising candidate for targeting ANXA2 in OC, warranting further experimental validation to confirm its therapeutic efficacy. 
  
   **keywords:** ovarian cancer; Apolipoproteins; Annexins; molecular docking; ADMET properties; MD simulation
---


# Introduction

OC is one of the leading causes of death in women, and the prognosis is heavily impacted by the disease’s stage [1]. OC is usually identified in its late stages since it is largely asymptomatic in its early stages. GI is one of the hallmarks of OC [2]. OC is classified into numerous categories, the most frequent of which is epithelial OC. GC tumors and stromal tumors are two less prevalent forms. OC can strike at any age, although it is more common in postmenopausal women. OC is caused by several risk factors, some of which are listed as follows: family history, genetic mutations (such as BRCA1 and BRCA2), age, and a history of breast, colorectal, or endometrial cancer may increase the risk of OC.

A physical examination, imaging tests and blood tests (including the CA-125 blood test, though it is not specific to OC) are commonly used to diagnose OC. Surgery to extract and evaluate the ovarian tissue is frequently used to get a definite diagnosis. Early detection is critical for improving OC prognosis. Regretfully, because the disease’s early-stage symptoms are not yet sufficiently distinguishable, it is frequently detected late. As a result, regular check-ups, being aware of risk factors, and paying attention to unusual symptoms can all help discover OC early [3]. APOs and ANXs have recently been linked to a variety of malignancies, including breast [4] and OC [5,6]. The overexpression of ANXA2 and its critical role in the progression of epithelial OC have been well-documented, specifically correlating high expression levels with poor patient survival outcomes [7,8].

APOs are proteins that join forces with lipids (fats) to create lipoproteins, which are essential for the bloodstream’s transit and metabolism of lipids [9]. While APOs are primarily associated with lipid transport and cholesterol metabolism, emerging research suggests that they may also have implications in cancer development and progression [10,11,12]. The link between cholesterol metabolism and cancer is an area of active research [13,14]. Lipids play a crucial role in cell membrane structure, and alterations in lipid metabolism can influence cancer cell growth and survival. Some cancer cells have an increased demand for cholesterol to support their rapid growth, and alterations in lipoprotein metabolism may contribute to cancer development [14,15]. For example, alterations in circulating levels of certain APOs may be associated with the presence or progression of certain cancers. The use of APOs as biomarkers is an evolving area of research and may have diagnostic or prognostic implications in the future [10,16].

On the other hand, ANXs are a family of calcium-dependent phospholipid-binding proteins that are involved in several cellular processes, such as membrane trafficking, apoptosis (PCD), inflammation, and the regulation of cellular signaling pathways [17,18]. Studies have linked ANXs to both normal cellular processes and the initiation and spread of different types of cancer. Apoptosis, a PCD mechanism necessary for preserving tissue homeostasis, may involve ANXs [19]. Dysregulation of apoptosis is a hallmark of cancer, and certain ANXs may influence whether cells undergo PCD or survive. ANXs have also been implicated in cell migration and invasion, critical processes in cancer metastasis. ANXs such as ANXA2 have been associated with promoting cell migration and invasion in some cancer types [20]. ANXs also contribute to TA, the creation of new blood vessels, which is crucial for tumor growth and progression. ANXA2, for example, has been linked to TA in prostate cancers [1], RCC [2], TNBC [3], esophageal cancer [4], etc. Some ANXs have been explored as potential diagnostic and prognostic markers for certain cancers [21], e.g., liver cancer [5], pancreatic cancer [6], colorectal cancer [9], etc. Given their involvement in OC, targeting signaling pathways of ANXs and APOs has emerged as a potential therapeutic strategy [22]. Preclinical and clinical studies are exploring approaches to inhibit ANXs and APOs or block their receptors to suppress tumor growth, TA, and metastasis, and enhance the effectiveness of existing treatments. The co-investigation of APOs and ANXs is biologically significant as they represent two pillars of the lipid-membrane interface. While the individual roles of APOs in metabolic transport and ANXs in structural scaffolding are recognized, their combined influence as a synchronized ‘lipid–membrane axis’ in OC progression remains poorly defined. We structured this study to test the hypothesis that the deadliest phenotypes of OC are driven by a synergy between the metabolic lipid availability provided by APOs and the structural membrane-remodeling capacity of ANXs. Consequently, our study design moves beyond simple expression profiling; we utilized a multi-omics filtration process to isolate family members that serve as both functional drivers and significant prognostic indicators of poor patient survival. While APOs orchestrate the metabolic availability of cholesterol and lipids necessary for rapid tumor growth, ANXs translate these lipid signals into structural membrane changes that facilitate invasion and metastasis. Together, their dysregulation in OC supports critical hallmarks such as TA, metabolic reprogramming, and evasion of apoptosis.

Turmeric’s natural ingredient, curcumin, has drawn significant attention due to its potential medical uses. By blocking several inflammatory pathways and lowering the synthesis of pro-inflammatory chemicals, curcumin demonstrates potent anti-inflammatory effects [23]. It can suppress the activity of TFs such as NF-κB, which play a key role in the inflammatory response in OC [24]. Curcumin has demonstrated the ability to modulate multiple signaling pathways, thereby showing promise in the management of inflammatory diseases such as RA [25], IBD [26], and CIDs [27]. Its anti-cancer potential, particularly in OC, has been widely explored [28]. The selection of curcumin as a therapeutic lead is grounded in established evidence demonstrating its capacity to modulate the protein–lipid interface. Prior investigations have shown that curcumin targets multiple enzymes in the ROS metabolic pathway to suppress tumor growth and acts as a synergistic regulator of the ANXA2, EGFR, and MMP signaling axes. While these studies documented curcumin’s influence on the ANXA2 pathway at the expression level, the physical stability of their direct interaction remains a critical research gap. This motivated our study to move beyond broad pathway modulation and investigate the structural feasibility of curcumin as a direct physical inhibitor of the ANXA2-binding domain.

Curcumin exerts its anti-tumor effects through various mechanisms [29], including inhibition of tumor growth, induction of apoptosis (PCD) in cancer cells [30], and suppression of TA. Moreover, it has been studied for its capacity to enhance the efficacy of chemotherapy and radiotherapy by sensitizing cancer cells to these treatments. As a natural phenolic compound, curcumin continues to gain attention for its therapeutic role in oncology research [31]. Over the years, it has been employed as a treatment strategy in various cancers, including LC [32] and OC [28], rather than being currently employed as a standard clinical treatment strategy. Beyond these broad anti-tumor effects, we selected curcumin as a candidate inhibitor because of its documented ability to modulate the protein–lipid interface. Given that ANXs function as phospholipid-binding scaffolds and APOs act as essential lipid-carrying mediators, we hypothesized that curcumin could physically disrupt the structural binding domains required for their activity. This investigation seeks to bridge the gap between curcumin’s known anti-metastatic properties and its potential to directly inhibit the ANXA2 and APOC2 proteins in OC phenotypes.

It may be advantageous to target a particular protein, and bioinformatics has made this feasible [33]. The transition from genomic identification to therapeutic targeting requires a precise understanding of structural compatibility. We adopted an integrated in silico pipeline that combines DGE with MD simulations to bridge the gap between biomarker identification and functional inhibition. This methodology allows for the simulation of physical ‘anchoring’ within the protein’s binding pocket, providing a structural rationale for inhibition that traditional expression analysis alone cannot provide. One potentially effective therapeutic approach to managing OC is to inhibit ANXs and APOs. It is crucial to remember that the roles played by ANXs and APOs in OC are complicated and might differ depending on the OC’s molecular features and subtypes. To gain a deeper understanding of the precise mechanisms and possible therapeutic implications of APOs and ANXs in the development and treatment of OC, more study is being conducted. In this study, we hypothesized that the dysregulation of specific ANX and APO family members drives OC progression and facilitates metastasis through altered membrane signaling. Consequently, we investigated curcumin as a potential therapeutic inhibitor that could directly target these prognostic markers. By integrating differential expression analysis, survival modeling, and MD simulations, we aim to characterize the structural and functional potential of the ANXA2–curcumin complex as a novel therapeutic strategy for OC.

While ANXA2 is a documented driver of epithelial OC progression, its activity is intrinsically linked to the availability of lipids at the membrane interface. Consequently, we initially investigated both the ANX and APO families to identify the most potent prognostic targets within this lipid–membrane axis. This dual-family approach served as a systematic selection filter, allowing us to objectively prioritize candidates with the highest differential expression and the strongest correlation to poor OS.

# Materials and Methods

# Results

# Discussion

# Conclusion


({{< words-abstract >}} words in abstract and {{< words-body >}} words in text body)


# References [-]




