---
title: "0. Install Required Packages"
format: 
  html:
    toc: true
    number-sections: true
---

```{r setup, include=FALSE, warning=FALSE}
if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr", dependencies = TRUE)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# Install required packages if missing
```{r}
# ############ Basic Environment & Development ############
if (!requireNamespace("curl", quietly = TRUE)) install.packages("curl", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("rmdwc", quietly = TRUE)) remotes::install_github("sigbertklinke/rmdwc", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("robustbase", quietly = TRUE)) install.packages("robustbase", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Data Processing & I/O ############

if (!requireNamespace("tidyverse", quietly = TRUE)) install.packages("tidyverse", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("data.table", quietly = TRUE)) install.packages("data.table", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("openxlsx", quietly = TRUE)) install.packages("openxlsx", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("reshape2", quietly = TRUE)) install.packages("reshape2", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("tidytext", quietly = TRUE)) install.packages("tidytext", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Parallel Computing & Progress ############
if (!requireNamespace("future", quietly = TRUE)) install.packages("future", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("furrr", quietly = TRUE)) install.packages("furrr", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("progressr", quietly = TRUE)) install.packages("progressr", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Bioconductor core & Annotation Packages ############
# core
if (!requireNamespace("GenomicRanges", quietly = TRUE)) 
    BiocManager::install("GenomicRanges", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("S4Vectors", quietly = TRUE)) 
    BiocManager::install("S4Vectors", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("IRanges", quietly = TRUE)) 
    BiocManager::install("IRanges", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("GenomeInfoDb", quietly = TRUE)) 
    BiocManager::install("GenomeInfoDb", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("BiocGenerics", quietly = TRUE)) 
    BiocManager::install("BiocGenerics", update = TRUE, force = TRUE, dependencies = TRUE)

# Annotation
if (!requireNamespace("org.Hs.eg.db", quietly = TRUE))
    BiocManager::install("org.Hs.eg.db", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("AnnotationDbi", quietly = TRUE))
    BiocManager::install("AnnotationDbi", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("TxDb.Hsapiens.UCSC.hg19.knownGene", quietly = TRUE))
    BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("hgu133plus2.db", quietly = TRUE)) 
    BiocManager::install("hgu133plus2.db", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("AnnoProbe", quietly = TRUE)) remotes::install_github("jmzeng1314/AnnoProbe", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Data Visualization ############
if (!requireNamespace("RColorBrewer", quietly = TRUE)) install.packages("RColorBrewer", update = TRUE, force = TRUE, dependencies = TRUE)

# ggplot
if (!requireNamespace("ggpubr", quietly = TRUE)) install.packages("ggpubr", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ggsci", quietly = TRUE)) install.packages("ggsci", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ggvenn", quietly = TRUE)) install.packages("ggvenn", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ggrepel", quietly = TRUE)) install.packages("ggrepel", update = TRUE, force = TRUE, dependencies = TRUE)

# corrplot
if (!requireNamespace("corrplot", quietly = TRUE)) install.packages("corrplot", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("ggcorrplot", quietly = TRUE))  install.packages("ggcorrplot")

# Manhattan Plot $ Quantile-Quantile Plot for GWAS
if (!requireNamespace("CMplot", quietly = TRUE)) install.packages("CMplot", update = TRUE, force = TRUE, dependencies = TRUE)

# heatmap
if (!requireNamespace("pheatmap", quietly = TRUE)) install.packages("pheatmap", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("circlize", quietly = TRUE)) install.packages("circlize", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ComplexHeatmap", quietly = TRUE))
    BiocManager::install("ComplexHeatmap", update = TRUE, force = TRUE, dependencies = TRUE)

# Combination images
if (!requireNamespace("cowplot", quietly = TRUE)) install.packages("cowplot", dependencies = TRUE)
if (!requireNamespace("patchwork", quietly = TRUE)) install.packages("patchwork", dependencies = TRUE)
if (!requireNamespace("gridExtra", quietly = TRUE)) install.packages("gridExtra", dependencies = TRUE)

# magic image processing
if (!requireNamespace("magick", quietly = TRUE)) install.packages("magick", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("rsvg", quietly = TRUE)) install.packages("rsvg", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("pdftools", quietly = TRUE)) install.packages("pdftools", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("rsvg", quietly = TRUE)) install.packages("rsvg", update = TRUE, force = TRUE, dependencies = TRUE)

# Network Analysis & Visualisation
if (!requireNamespace("igraph", quietly = TRUE)) install.packages("igraph", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("centiserve", quietly = TRUE)) install.packages("centiserve", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("RCy3", quietly = TRUE)) BiocManager::install("RCy3", update = TRUE, force = TRUE, dependencies = TRUE)

# Sankey diagram
if (!requireNamespace("networkD3", quietly = TRUE)) install.packages("networkD3", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ggalluvial", quietly = TRUE)) install.packages("ggalluvial", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("ggsankeyfier", quietly = TRUE)) install.packages("ggsankeyfier", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Differential expression analysis & WGCNA ############
if (!requireNamespace("limma", quietly = TRUE))  BiocManager::install("limma", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("DESeq2", quietly = TRUE))  BiocManager::install("DESeq2", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("edgeR", quietly = TRUE))  BiocManager::install("edgeR", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("preprocessCore", quietly = TRUE))  BiocManager::install("preprocessCore", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("WGCNA", quietly = TRUE)) 
BiocManager::install("WGCNA", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Enrichment & Gene Set Analysis ############
if (!requireNamespace("clusterProfiler", quietly = TRUE)) 
    BiocManager::install("clusterProfiler", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("GSVA", quietly = TRUE)) BiocManager::install("GSVA", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("AUCell", quietly = TRUE)) BiocManager::install("AUCell", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Immuno-Oncology & Microenvironment ############
if (!requireNamespace("IOBR", quietly = TRUE)) remotes::install_github("IOBR/IOBR", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("HPAanalyze", quietly = TRUE)) 
    BiocManager::install("HPAanalyze", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Genetic Causality (MR & Colocalization) ############
# TwoSampleMR
if (!requireNamespace("TwoSampleMR", quietly = TRUE)) remotes::install_github("MRCIEU/TwoSampleMR", update = TRUE, force = TRUE, dependencies = TRUE)

if (!requireNamespace("coloc", quietly = TRUE)) 
    BiocManager::install("coloc", update = TRUE, force = TRUE, dependencies = TRUE)

# ############ Single-Cell Omics ############
if (!requireNamespace("SeuratObject", quietly = TRUE)) 
    BiocManager::install("SeuratObject", update = TRUE, force = TRUE, dependencies = TRUE)
if (!requireNamespace("Seurat", quietly = TRUE)) 
    BiocManager::install("Seurat", update = TRUE, force = TRUE, dependencies = TRUE)
```

---
# Clean cache

```{r}
# clean 
clean_install_cache <- function() {
  unlink(file.path(tempdir(), "*"), recursive = TRUE, force = TRUE)

  cache_dir <- tools::R_user_dir("", which = "cache")
  if (dir.exists(cache_dir)) {
    unlink(file.path(cache_dir, "*"), recursive = TRUE, force = TRUE)
    message("Cleaned R cache: ", cache_dir)
  }

  gc()
  message("Install cache cleaned.")
}

clean_install_cache()

rm(list = ls())
```

# Terminal

- running at Terminal 

```{base}
quarto add andrewheiss/quarto-wordcount

# YAML Settings of QMD file （ HTML / PDF / Word）
# format:
#   # html:
#   wordcount-html:
  
# Placed on the last line of the entire text
# ({{< words-abstract >}} words in abstract and {{< words-body >}} words in text body)
```

