---
title: " 04_organ_localization_meridian_tropism"
format: 
  wordcount-html:
    toc: true
    number-sections: true
---

```{r setup, include=FALSE, warning=FALSE}
if (!requireNamespace("knitr", quietly = TRUE)) install.packages("knitr", dependencies = TRUE)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.dpi = 300,
  fig.align = "center"
)

options(timeout = 36000)
options(stringsAsFactors = FALSE)
options(download.file.method = "curl")
options(download.file.extra = "-k -L")

options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
```

# Load packages {-}
```{r}
library(tidyverse)
library(data.table)
library(openxlsx)
library(tidytext)

library(pheatmap)
library(igraph)
library(ggsci)
library(ggrepel)
library(ComplexHeatmap)
library(circlize)
library(magick)
library(rsvg)
library(pdftools)

# library(hgu133a.db)
library(hgu133plus2.db)
library(AnnotationDbi)
library(HPAanalyze)
library(org.Hs.eg.db)
```

# 
```{r}
rm(list = ls())
gc()

# BioGPS
expr_bio <- read.csv("../data/raw/organ/U133AGNF1B.gcrma.avg.csv", row.names = 1, check.names = FALSE)

dim(expr_bio)  
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```

# 
```{r}
```
